"""Exact port of @forcedream/mcp-server's verify_proof.ts.

The Ed25519 verification mechanics (PEM public key loading, raw-digest-bytes-as-message,
base64 signature decoding) were cross-tested against a real signature generated by Node's
node:crypto using the exact same signing approach the real server uses, before this file
was written -- confirmed correct, and confirmed to correctly reject tampered data.
"""
import base64
from typing import Optional, TypedDict, Union
import httpx
from cryptography.hazmat.primitives.serialization import load_pem_public_key
from cryptography.exceptions import InvalidSignature

from .canonical import wf_canonical, sha256_hex


class FdProof(TypedDict, total=False):
    task_id: str
    agent_id: str
    input_hash: str
    output_hash: str
    cost_pence: Union[int, str]
    budget_pence: Union[int, str]
    external_cost_hash: Optional[str]
    retrieved_count: Optional[int]
    started_at: Union[int, str]
    completed_at: Union[int, str]
    algorithm: Optional[str]
    signature: Optional[str]
    key_id: Optional[str]
    worm_seal: Optional[str]
    proof_id: Optional[str]


class VerifyResult(TypedDict):
    verified: bool
    task_id: str
    key_id: Optional[str]
    algorithm: str
    fields_signed: int
    trustless: bool
    message: str
    note: str


def _js_number(value) -> Union[int, float]:
    """Replicates JS's Number(x) -> JSON.stringify behavior exactly: whole-valued numbers
    serialize without a decimal point, fractional ones keep their precision. Verified by
    direct cross-test against real JS output before this was trusted -- a naive int()
    coercion here would silently truncate any real proof with fractional timestamps."""
    n = float(value)
    return int(n) if n.is_integer() else n


def _build_signable(p: FdProof) -> tuple[dict, int]:
    """Reconstruct the signable EXACTLY as the server did. Version-aware: proofs with
    external_cost_hash were signed over 10 fields, older ones over 8. Types matter --
    cost_pence, budget_pence, retrieved_count, started_at are NUMBERS; completed_at is a
    STRING. Ported field-for-field, coercion-for-coercion from the real source."""
    has_ext = p.get('external_cost_hash') is not None
    base = {
        'task_id': p['task_id'],
        'agent_id': p['agent_id'],
        'input_hash': p['input_hash'],
        'output_hash': p['output_hash'],
        'cost_pence': _js_number(p['cost_pence']),
        'budget_pence': _js_number(p['budget_pence']),
        'started_at': _js_number(p['started_at']),
        'completed_at': str(p['completed_at']),
    }
    if has_ext:
        base['external_cost_hash'] = str(p['external_cost_hash'])
        base['retrieved_count'] = _js_number(p.get('retrieved_count') or 0)
        # Model binding: the server records which provider and model actually served
        # the execution and binds them into the signed payload. Conditional, so a
        # proof issued before this existed canonicalises exactly as it did then --
        # adding them unconditionally would break every proof already in the wild.
        n = 10
        if p.get('inference_provider'):
            base['inference_provider'] = str(p['inference_provider'])
            n += 1
        if p.get('inference_model'):
            base['inference_model'] = str(p['inference_model'])
            n += 1
        return base, n
    return base, 8


# Every field this SDK version knows how to canonicalise. Anything else in a proof
# means the server signed over something this version cannot reconstruct -- which is
# a version gap, not evidence of tampering, and must not be reported as tampering.
_KNOWN_SIGNED_FIELDS = {
    'task_id', 'agent_id', 'input_hash', 'output_hash', 'cost_pence', 'budget_pence',
    'started_at', 'completed_at', 'external_cost_hash', 'retrieved_count',
    'inference_provider', 'inference_model',
}

# Present on a proof but never part of the signed payload -- transport and envelope.
_UNSIGNED_FIELDS = {
    'proof_id', 'key_id', 'algorithm', 'merkle_root', 'batch_id', 'batch_size',
    'inclusion_proof', 'worm_seal', 'signature', 'created_at',
}


def _unknown_fields(p: FdProof) -> list:
    """Fields this SDK version does not recognise. Their presence explains a failed
    verification honestly: the payload was signed over something we cannot rebuild."""
    return sorted(set(p) - _KNOWN_SIGNED_FIELDS - _UNSIGNED_FIELDS)


async def verify_proof(
    api_base: str,
    task_id: Optional[str] = None,
    proof: Optional[FdProof] = None,
) -> VerifyResult:
    """Trustlessly verifies a ForceDream proof's Ed25519 signature entirely client-side.
    ForceDream is never asked whether the proof is valid -- the math decides, locally."""
    async with httpx.AsyncClient(timeout=httpx.Timeout(30.0)) as client:
        if proof is None:
            if task_id is None:
                raise ValueError('Provide task_id or proof')
            res = await client.get(f'{api_base}/v1/workforce/proof/{task_id}/public')
            if res.status_code != 200:
                raise RuntimeError(f'fetch proof -> HTTP {res.status_code}')
            data = res.json()
            if not data.get('proof'):
                raise RuntimeError('proof_not_found')
            proof = data['proof']

        key_res = await client.get(f'{api_base}/v1/workforce/proof/public-key')
        if key_res.status_code != 200:
            raise RuntimeError(f'fetch public key -> HTTP {key_res.status_code}')
        key_data = key_res.json()

    pub = load_pem_public_key(key_data['public_key_pem'].encode())

    signable, fields = _build_signable(proof)
    digest_hex = sha256_hex(wf_canonical(signable))

    # Real fix: previously only ever attempted verification when algorithm ==
    # 'Ed25519' or absent -- any real Ed25519-batched proof (Merkle-root signing,
    # used to amortize signing cost across a batch) fell through with verified
    # left at its initial False, reporting a hard "signature verification FAILED"
    # for a proof that was never actually checked. Confirmed against two real,
    # live, settled proofs before this fix was trusted: both use
    # Ed25519-batched and both now correctly verify True.
    verified = False
    signature = proof.get('signature')
    algorithm = proof.get('algorithm') or 'Ed25519'
    is_batched = algorithm == 'Ed25519-batched'

    if signature and algorithm in ('Ed25519', 'Ed25519-batched'):
        try:
            if is_batched:
                root = str(proof.get('merkle_root') or '')
                inclusion = proof.get('inclusion_proof') or {}
                siblings = inclusion.get('siblings', [])
                if not root or not isinstance(siblings, list):
                    check_hex = None
                else:
                    current = digest_hex
                    for step in siblings:
                        if step.get('position') == 'right':
                            current = sha256_hex(current + step['hash'])
                        else:
                            current = sha256_hex(step['hash'] + current)
                    check_hex = current if current == root else None
            else:
                check_hex = digest_hex

            if check_hex is not None:
                check_bytes = bytes.fromhex(check_hex)
                signature_bytes = base64.b64decode(signature)
                pub.verify(signature_bytes, check_bytes)
                verified = True
        except (InvalidSignature, Exception):
            verified = False

    return VerifyResult(
        verified=verified,
        task_id=proof['task_id'],
        key_id=key_data.get('key_id'),
        algorithm=algorithm,
        fields_signed=fields,
        trustless=True,
        message=(
            (
                'Signature mathematically verified against a real, independently-reconstructed Merkle root. Signed by ForceDream, unaltered.'
                if is_batched else
                'Signature mathematically verified. This proof was signed by ForceDream and has not been altered.'
            )
            if verified else
            (('Signature could not be verified: this proof carries fields this SDK version does not know (' + ', '.join(_unknown_fields(proof)) + '). Upgrade the SDK -- the proof itself may be perfectly valid.') if _unknown_fields(proof) else 'Signature verification FAILED. The proof was altered or not signed by ForceDream.')
        ),
        note='Verified client-side via public-key cryptography. ForceDream was not asked whether the proof is valid.',
    )
